#-Basic info----------------------------------------------------------------------------------------
display_name: sp_ecoli
name: sp_ecoli__v0.0.1
version:
  schema: ["v2_1_0"]
  code: v0.0.1
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    Ecoli related analysis.
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [serotype]
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  db: "ecoli_fbi/db/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      species_detection:
        summary:
          species: Escherichia coli
  components:
    analyzer:
      status:
#---------------------------------------------------------------------------------------------------
