name: bifrost sp ecoli workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:  # webhook event to trigger this action workflow upon push to the submodule ecoli_fbi 
    types: 
      - ecoli-fbi-webhook 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
  
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'  #Initialize and update submodules -> git submodule init && git submodule update
        
      # Step 2: Update submodule to the latest commit
      - name: Update submodule
        run: |
          cd bifrost_sp_ecoli/ecoli_fbi

          # Show the current commit hash before updating
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit hash of ecoli_fbi before update: $CURRENT_COMMIT"
          
          echo "Fetching latest changes from origin"
          git fetch origin

          echo "Switching to the main branch and pulling latest updates"
          git checkout main  # or the specific branch you want to track
          git pull origin main  # pull the latest changes
          
          # Show the new commit hash after the update
          LATEST_COMMIT=$(git rev-parse HEAD)
          echo "Updated commit hash of ecoli_fbi after update: $LATEST_COMMIT"

          # print the latest tag of ecoli_fbi
          LATEST_TAG_COMMIT=$(git tag --sort=-creatordate --format '%(objectname)'|head -1)
          LATEST_TAG=$(git tag --sort=-creatordate|head -1)
          
          #echo "test 1" - git tag - ecoli_fbi.51ea941.01-11-2024
          #echo "test 2" - git show-ref --tags -d - 51ea9416c35d4f6e9496a4dfd0e6e4c9ad83f6ba refs/tags/ecoli_fbi.51ea941.01-11-2024
          #echo "test 3" - git describe --abbrev=0 --tags - ecoli_fbi.51ea941.01-11-2024
          #echo "test 4" - git ls-remote --tags origin - 51ea9416c35d4f6e9496a4dfd0e6e4c9ad83f6ba	refs/tags/ecoli_fbi.51ea941.01-11-2024 \n c57a577e5568623a0f780f581d47a132aa7c3413	refs/tags/ecoli_fbi.c57a577.01-11-2024
          echo $(git show-ref --tags -d | cut -f1 -d ' ' | sed 's|.*/||')
          echo $(git show-ref --tags -d | cut -f2 -d ' ' | sed 's|.*/||')
          echo "test 4"
          echo $(git ls-remote --tags origin | cut -f1 | head -1 | awk -F'/' '{print $NF}')
          echo $(git ls-remote --tags origin | cut -f2 | head -1 | sed 's|.*/||')
          echo $(git ls-remote --tags origin | cut -f2 | head -1 | awk -F'/' '{print $NF}')
          echo $(git ls-remote --tags origin | cut -f2 | head -1 | sed 's|.*/||')
          echo "Checking commit hash for the latest tag of ecoli_fbi: $LATEST_TAG_COMMIT"
          echo "Checking the lastest tag of ecoli_fbi: $LATEST_TAG"
          
          git checkout $LATEST_TAG_COMMIT 

      # Step 3: Set environment variables
      - name: Set environment variables
        run: |
          echo "BIFROST_INSTALL_DIR='${{ github.workspace }}'" >> $GITHUB_ENV

      # Step 4: Extract version from __init__.py and set ENV_NAME
      - name: Set ENV_NAME
        run: |
          VERSION=$(grep "__version__" bifrost_sp_ecoli/__init__.py | cut -d "'" -f 2)
          REPO_NAME=$(basename "${{ github.workspace }}")
          ENV_NAME="${REPO_NAME}_v${VERSION}"
          # Echo the ENV_NAME to the log for debugging
          echo "Setting ENV_NAME to: $ENV_NAME"
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_ENV

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build --build-arg BIFROST_DB_KEY="${{ secrets.MONGODB_ATLAS_TEST }}" --build-arg CONDA_ENV_NAME="${{ env.ENV_NAME }}" -t bifrost_sp_ecoli_image .

      # Step 6: Run Docker container and execute the command
      - name: Run Docker container
        run: |
          docker run --env BIFROST_DB_KEY="${{ secrets.MONGODB_ATLAS_TEST  }}" --env CONDA_ENV_NAME="${{ env.ENV_NAME }}" bifrost_sp_ecoli_image