name: bifrost sp ecoli workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'  #Initialize and update submodules -> git submodule init && git submodule update
        
      # Step 2: Set environment variables
      - name: Set environment variables
        run: |
          echo "BIFROST_INSTALL_DIR='${{ github.workspace }}'" >> $GITHUB_ENV

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          docker build \
          --build-arg BIFROST_DB_KEY=${{ secrets.MONGODB_ATLAS_CONNECTION }} \
          -t bifrost_sp_ecoli_image . 
      # docker build -t bifrost_sp_ecoli_image -f /path/to/your/Dockerfile .

      # Step 4: Run tests in Docker container
      - name: Run tests
        run: |
          docker run --rm \
          -e BIFROST_INSTALL_DIR='${{ github.workspace }}' \
          -e BIFROST_DB_KEY='${{ secrets.MONGODB_ATLAS_CONNECTION }}' \
          bifrost_sp_ecoli_image \
          bash -c "conda activate $ENV_NAME && pytest"